CREATE TABLE product(
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) UNIQUE NOT NULL,
    description TEXT
);

ALTER TABLE product ADD COLUMN user_id INTEGER REFERENCES users(id);
ALTER TABLE product
ADD COLUMN image_url VARCHAR(255),
ADD COLUMN price DECIMAL(10, 2);


ALTER TABLE product DROP CONSTRAINT product_title_key;

CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE users ADD COLUMN gravatar VARCHAR(255);